### ISSUE TITLE
How do i install this on arch?

### ISSUE THREAD

**Issue by Xorger** [telent/schlock#1]
Hello, i have a pinephone with arch and would like to use this on that however there are only install instructions for nix, and no i dont want to install nix for just one package so any help is appriceated

**Comment by pt1997** [comment]
```
git clone https://github.com/telent/schlock.git
cd schlock/
meson build
ninja -C build
sudo ninja -C build install
mkpin > $HOME/.config/schlock.pin
```

`schlock --pin-file $HOME/.config/schlock.pin`

I tried to use it on the PinePhone Pro, but it appears to not work with Hyprland. On sway I tried it only once, that time it worked.
@Xorger have you found another solution?

**Comment by Xorger** [comment]
thank you, unfortuanatly it's too late now and i completley forgot about this issue, anyways this seems mostly unmaintained so i won't be using it.
